export const landingRedesign = {
  en: {
    nav: { home: "Home", about: "About us", farmers: "For farmers", customers: "For customers", how: "How it works", login: "Log in", start: "Get started", language: "Language", menu: "Open menu" },
    hero: { eyebrow: "From farmer to customer", title: "Your crop,\ndirect to customers.", body: "Sell with clarity, meet the people who buy your produce, and keep the journey simple from field to home.", sell: "Start selling", buy: "Buy fresh produce", imageAlt: "Farmer standing beside rows of fresh produce", farmer: "Farmer", customer: "Customer", bridge: "DIRECT FARM", bridgeBody: "A clear, direct marketplace", trust: ["Verified farmers", "Fair, visible prices", "Fresh produce", "Safe payments"] },
    value: { eyebrow: "A simpler mandi", title: "A direct path from the field to the home.", body: "Commercial middlemen are removed. Delivery can still be handled by the farmer, the customer, or a delivery service.", farmer: "Farmer", farmerBody: "Lists produce and sets a price", platform: "DIRECT FARM", platformBody: "Brings both sides together", customer: "Customer", customerBody: "Discovers and orders fresh produce" },
    how: { eyebrow: "How it works", title: "Four steps. One clear journey.", steps: [["01", "Add your crop", "Add a photo, availability and the details customers need."], ["02", "Set your price", "Choose your selling price or use helpful market guidance."], ["03", "Receive an order", "A customer orders your produce directly from your listing."], ["04", "Send it on its way", "Arrange pickup, delivery or a service that works for both sides."]] },
    benefits: { eyebrow: "For farmers", title: "More control over every sale.", body: "The tools you need to present your farm clearly, sell directly and understand what is happening with each order.", cards: [["Your price", "You decide the selling price for your produce."], ["Direct customers", "Build a relationship with the people buying your crop."], ["Simple orders", "See your listings and orders in one calm workspace."], ["Clear earnings", "Understand your sales without hunting through records."], ["Farm identity", "Help customers learn about your field and your way of growing."], ["Verified profile", "Build confidence with a profile that can be checked."]] },
    story: { eyebrow: "The person behind the produce", title: "A farmer is more than a seller.", body: "Customers can know where their food came from, how it was grown and who they are supporting.", demo: "Sample profile", farmer: "Sample farmer", place: "Sidhpur, Gujarat", farm: "12 acres of farmland", crops: "Tomatoes, potatoes and onions", badge: "Verified farmer", cta: "Explore farmer stories", imageAlt: "Farmer working in a vegetable field" },
    passport: { eyebrow: "Digital crop passport", title: "Know the journey behind every crop.", body: "From sowing to packing, a simple record helps customers understand what they are buying.", steps: ["Sowing", "Growing", "Ready to harvest", "Harvesting", "Packing", "To customer"], qr: "Scan the QR code to learn more about this crop.", cta: "See a crop journey" },
    customer: { eyebrow: "For customers", title: "Fresh produce, with a story you can follow.", body: "Find produce from farmers, see useful crop information and choose a delivery option that suits you.", cards: [["Fresh from the field", "Buy produce directly from the source."], ["Know the farmer", "See who grew the crop you are buying."], ["Crop information", "Follow the journey from sowing to harvest."], ["Flexible delivery", "Choose pickup or delivery as available."]], cta: "Explore the market", imageAlt: "Fresh vegetables arranged for market" },
    final: { title: "Bring the field closer to home.", body: "A simpler digital mandi for farmers and customers.", farmer: "I am a farmer", customer: "I am a customer" },
    footer: { tagline: "From farmer to customer, directly.", explore: "Explore", farmers: "For farmers", customers: "For customers", how: "How it works", contact: "Contact", legal: "Legal", privacy: "Privacy", terms: "Terms", copyright: "© 2026 DIRECT FARM. All rights reserved." }
  },
  hi: {
    nav: { home: "होम", about: "हमारे बारे में", farmers: "किसानों के लिए", customers: "ग्राहकों के लिए", how: "कैसे काम करता है", login: "लॉग इन", start: "शुरू करें", language: "भाषा", menu: "मेन्यू खोलें" },
    hero: { eyebrow: "किसान से ग्राहक तक", title: "आपकी फसल,\nसीधे ग्राहकों तक।", body: "अपनी फसल साफ़ तरीके से बेचें, खरीदने वालों से जुड़ें और खेत से घर तक का सफर आसान रखें।", sell: "बेचना शुरू करें", buy: "ताज़ी फसल खरीदें", imageAlt: "ताज़ी फसल के पास खड़ा किसान", farmer: "किसान", customer: "ग्राहक", bridge: "DIRECT FARM", bridgeBody: "एक सीधा और साफ़ बाज़ार", trust: ["सत्यापित किसान", "साफ़ और उचित भाव", "ताज़ी फसल", "सुरक्षित भुगतान"] },
    value: { eyebrow: "सरल मंडी", title: "खेत से घर तक का सीधा रास्ता।", body: "व्यावसायिक बिचौलियों को हटाया जाता है। डिलीवरी किसान, ग्राहक या डिलीवरी सेवा संभाल सकती है।", farmer: "किसान", farmerBody: "फसल और भाव साझा करता है", platform: "DIRECT FARM", platformBody: "दोनों को एक साथ लाता है", customer: "ग्राहक", customerBody: "ताज़ी फसल खोजकर ऑर्डर करता है" },
    how: { eyebrow: "कैसे काम करता है", title: "चार कदम। एक साफ़ सफर।", steps: [["01", "फसल जोड़ें", "फोटो, उपलब्धता और ग्राहक के लिए ज़रूरी जानकारी जोड़ें।"], ["02", "भाव तय करें", "अपना भाव रखें या बाज़ार की मददगार जानकारी देखें।"], ["03", "ऑर्डर पाएँ", "ग्राहक आपकी फसल को सीधे आपकी सूची से खरीदता है।"], ["04", "फसल पहुँचाएँ", "किसान, ग्राहक या डिलीवरी सेवा के अनुसार व्यवस्था करें।"]] },
    benefits: { eyebrow: "किसानों के लिए", title: "हर बिक्री पर आपका ज़्यादा नियंत्रण।", body: "अपने खेत को साफ़ तरीके से दिखाएँ, सीधे बेचें और हर ऑर्डर की जानकारी आसानी से समझें।", cards: [["आपका भाव", "अपनी फसल का बिक्री भाव आप तय करें।"], ["सीधे ग्राहक", "फसल खरीदने वाले लोगों से जुड़ें।"], ["आसान ऑर्डर", "लिस्टिंग और ऑर्डर एक ही जगह देखें।"], ["साफ़ कमाई", "बिक्री और कमाई की जानकारी आसानी से देखें।"], ["खेत की पहचान", "ग्राहकों को अपने खेत और खेती के बारे में बताएँ।"], ["सत्यापित प्रोफ़ाइल", "जाँची जा सकने वाली प्रोफ़ाइल से भरोसा बनाएँ।"]] },
    story: { eyebrow: "फसल के पीछे का किसान", title: "किसान सिर्फ़ बेचने वाला नहीं है।", body: "ग्राहक जान सकते हैं कि उनका खाना कहाँ से आया, कैसे उगा और किस किसान का साथ दे रहे हैं।", demo: "नमूना प्रोफ़ाइल", farmer: "नमूना किसान", place: "सिद्धपुर, गुजरात", farm: "12 एकड़ खेत", crops: "टमाटर, आलू और प्याज़", badge: "सत्यापित किसान", cta: "किसानों की कहानी देखें", imageAlt: "सब्ज़ी के खेत में काम करता किसान" },
    passport: { eyebrow: "डिजिटल फसल पासपोर्ट", title: "हर फसल का सफर जानें।", body: "बुवाई से पैकिंग तक, एक आसान रिकॉर्ड ग्राहक को उसकी खरीद समझने में मदद करता है।", steps: ["बुवाई", "बढ़त", "फसल तैयार", "कटाई", "पैकिंग", "ग्राहक तक"], qr: "फसल के बारे में जानने के लिए QR कोड स्कैन करें।", cta: "फसल का सफर देखें" },
    customer: { eyebrow: "ग्राहकों के लिए", title: "ताज़ी फसल, जिसकी कहानी आप जान सकते हैं।", body: "किसानों की फसल खोजें, उपयोगी जानकारी देखें और अपनी सुविधा की डिलीवरी चुनें।", cards: [["खेत से ताज़ी", "फसल सीधे उसके स्रोत से खरीदें।"], ["किसान को जानें", "जानें कि आपकी फसल किसने उगाई।"], ["फसल की जानकारी", "बुवाई से कटाई तक का सफर देखें।"], ["सुविधाजनक डिलीवरी", "जहाँ उपलब्ध हो, पिकअप या डिलीवरी चुनें।"]], cta: "बाज़ार देखें", imageAlt: "बाज़ार के लिए रखी ताज़ी सब्ज़ियाँ" },
    final: { title: "खेत को घर के और करीब लाएँ।", body: "किसानों और ग्राहकों के लिए एक सरल डिजिटल मंडी।", farmer: "मैं किसान हूँ", customer: "मैं ग्राहक हूँ" },
    footer: { tagline: "किसान से ग्राहक तक, सीधे।", explore: "देखें", farmers: "किसानों के लिए", customers: "ग्राहकों के लिए", how: "कैसे काम करता है", contact: "संपर्क", legal: "कानूनी", privacy: "गोपनीयता", terms: "शर्तें", copyright: "© 2026 DIRECT FARM. सर्वाधिकार सुरक्षित।" }
  },
  gu: {
    nav: { home: "ઘર", about: "અમારા વિશે", farmers: "ખેડૂતો માટે", customers: "ગ્રાહકો માટે", how: "કેવી રીતે કામ કરે છે", login: "લૉગ ઇન", start: "શરૂ કરો", language: "ભાષા", menu: "મેનુ ખોલો" },
    hero: { eyebrow: "ખેડૂતથી સીધો ગ્રાહક સુધી", title: "તમારો પાક,\nસીધો ગ્રાહકો સુધી.", body: "તમારો પાક સરળતાથી વેચો, ખરીદનાર લોકો સાથે જોડાઓ અને ખેતરથી ઘર સુધીનો રસ્તો સરળ રાખો.", sell: "પાક વેચવાનું શરૂ કરો", buy: "તાજો પાક ખરીદો", imageAlt: "તાજા પાકની બાજુમાં ઊભેલો ખેડૂત", farmer: "ખેડૂત", customer: "ગ્રાહક", bridge: "DIRECT FARM", bridgeBody: "સરળ અને સીધું બજાર", trust: ["ચકાસાયેલ ખેડૂત", "પારદર્શક ભાવ", "તાજો પાક", "સુરક્ષિત ચુકવણી"] },
    value: { eyebrow: "સરળ મંડી", title: "ખેતરથી ઘર સુધીનો સીધો રસ્તો.", body: "વેપારી વચેટિયાઓ દૂર થાય છે. ડિલિવરી ખેડૂત, ગ્રાહક અથવા ડિલિવરી સેવા દ્વારા થઈ શકે છે.", farmer: "ખેડૂત", farmerBody: "પાક અને ભાવની માહિતી આપે છે", platform: "DIRECT FARM", platformBody: "બંનેને એક જગ્યાએ જોડે છે", customer: "ગ્રાહક", customerBody: "તાજો પાક શોધીને ઓર્ડર કરે છે" },
    how: { eyebrow: "કેવી રીતે કામ કરે છે", title: "ચાર પગલાં. એક સરળ સફર.", steps: [["01", "પાક ઉમેરો", "ફોટો, ઉપલબ્ધતા અને ગ્રાહક માટે જરૂરી માહિતી ઉમેરો."], ["02", "ભાવ નક્કી કરો", "તમારો વેચાણ ભાવ નક્કી કરો અથવા બજારની મદદ લો."], ["03", "ઓર્ડર મેળવો", "ગ્રાહક તમારી યાદીમાંથી સીધો પાક ખરીદે છે."], ["04", "પાક પહોંચાડો", "ખેડૂત, ગ્રાહક અથવા ડિલિવરી સેવા પ્રમાણે વ્યવસ્થા કરો."]] },
    benefits: { eyebrow: "ખેડૂતો માટે", title: "દરેક વેચાણ પર તમારું વધારે નિયંત્રણ.", body: "તમારા ખેતરને સારી રીતે બતાવો, સીધું વેચો અને દરેક ઓર્ડરની માહિતી સરળતાથી સમજો.", cards: [["તમારો ભાવ", "તમારા પાકનો વેચાણ ભાવ તમે નક્કી કરો."], ["સીધા ગ્રાહકો", "તમારો પાક ખરીદતા લોકો સાથે જોડાઓ."], ["સરળ ઓર્ડર", "તમારી યાદી અને બધા ઓર્ડર એક જ જગ્યાએ જુઓ."], ["તમારી કમાણી", "વેચાણ અને કમાણીની માહિતી સરળતાથી જુઓ."], ["ખેતરની ઓળખ", "ગ્રાહકોને તમારા ખેતર અને ખેતી વિશે જણાવો."], ["ચકાસાયેલ પ્રોફાઇલ", "ચકાસી શકાય તેવી પ્રોફાઇલથી વિશ્વાસ બનાવો."]] },
    story: { eyebrow: "પાક પાછળનો ખેડૂત", title: "ખેડૂત માત્ર વેચનાર નથી.", body: "ગ્રાહક જાણી શકે છે કે તેનો ખોરાક ક્યાંથી આવ્યો, કેવી રીતે ઉગ્યો અને તે કોને સહકાર આપી રહ્યો છે.", demo: "નમૂનાની પ્રોફાઇલ", farmer: "નમૂનાના ખેડૂત", place: "સિદ્ધપુર, ગુજરાત", farm: "12 એકર ખેતર", crops: "ટામેટાં, બટાકા અને ડુંગળી", badge: "ચકાસાયેલ ખેડૂત", cta: "ખેડૂતની વાર્તા જુઓ", imageAlt: "શાકભાજીના ખેતરમાં કામ કરતો ખેડૂત" },
    passport: { eyebrow: "ડિજિટલ પાક પાસપોર્ટ", title: "દરેક પાકની સફર જાણો.", body: "વાવણીથી પેકિંગ સુધીની સરળ માહિતી ગ્રાહકને તેની ખરીદી સમજવામાં મદદ કરે છે.", steps: ["વાવણી", "ઉછેર", "પાક તૈયાર", "કાપણી", "પેકિંગ", "ગ્રાહક સુધી"], qr: "પાક વિશે વધુ જાણવા QR કોડ સ્કેન કરો.", cta: "પાકની સફર જુઓ" },
    customer: { eyebrow: "ગ્રાહકો માટે", title: "તાજો પાક, તેની સંપૂર્ણ ઓળખ સાથે.", body: "ખેડૂતો પાસેથી પાક શોધો, જરૂરી માહિતી જુઓ અને તમારી અનુકૂળ ડિલિવરી પસંદ કરો.", cards: [["ખેતરમાંથી તાજો", "પાક સીધો તેના મૂળ સ્ત્રોત પાસેથી ખરીદો."], ["ખેડૂતને ઓળખો", "તમારો પાક કોણે ઉગાડ્યો તે જાણો."], ["પાકની માહિતી", "વાવણીથી કાપણી સુધીની સફર જુઓ."], ["સરળ ડિલિવરી", "ઉપલબ્ધતા પ્રમાણે પિકઅપ અથવા ડિલિવરી પસંદ કરો."]], cta: "બજાર જુઓ", imageAlt: "બજાર માટે ગોઠવેલા તાજા શાકભાજી" },
    final: { title: "ખેતરને ઘર સુધી વધારે નજીક લાવો.", body: "ખેડૂતો અને ગ્રાહકો માટેની સરળ ડિજિટલ મંડી.", farmer: "હું ખેડૂત છું", customer: "હું ગ્રાહક છું" },
    footer: { tagline: "ખેડૂતથી ગ્રાહક સુધી, સીધું.", explore: "જુઓ", farmers: "ખેડૂતો માટે", customers: "ગ્રાહકો માટે", how: "કેવી રીતે કામ કરે છે", contact: "સંપર્ક", legal: "કાયદાકીય", privacy: "ગોપનીયતા", terms: "શરતો", copyright: "© 2026 DIRECT FARM. સર્વ હકો સુરક્ષિત." }
  }
} as const;
