export const workspaceGujarati = {
  nav: {
    home: "ઘર", market: "પાકનું બજાર", orders: "ઓર્ડર", payments: "ચુકવણી", chat: "સંદેશા", weather: "હવામાન", intel: "ખેતીની માહિતી", calendar: "પાકનું કૅલેન્ડર", schemes: "સરકારી યોજનાઓ", farmer: "ખેડૂતનું ખાતું", lots: "મારા પાક", admin: "વહીવટ", account: "મારું ખાતું", cart: "પસંદ કરેલા પાક", wishlist: "સાચવેલા પાક", farmers: "ખેડૂતો", login: "પ્રવેશ કરો", logout: "બહાર નીકળો"
  },
  common: { menu: "મેનુ", language: "ભાષા", skip: "મુખ્ય સામગ્રી પર જાઓ", viewAll: "બધું જુઓ", close: "બંધ કરો", search: "શોધો", back: "પાછા જાઓ", loading: "માહિતી લાવી રહ્યા છીએ...", organic: "સજીવ", verified: "ચકાસાયેલું ખેતર" },
  farmerNav: { home: "મારું કામ", products: "મારા પાક", orders: "મારા ઓર્ડર", earnings: "મારી કમાણી", farm: "મારું ખેતર", more: "વધુ માહિતી", weather: "હવામાન", messages: "સંદેશા", settings: "મારી સેટિંગ્સ" },
  farmerHeader: { searchPlaceholder: "શું શોધવું છે?" },
  desk: {
    kicker: "વહીવટનું કેન્દ્ર", title: "DIRECT FARM વહીવટ", lede: "ખેડૂત, ગ્રાહક, પાક અને ઓર્ડરની માહિતી એક જ સરળ જગ્યાએ જુઓ.", overview: "આજની સ્થિતિ", overviewLede: "બજારની મહત્વની માહિતી એક નજરે.", users: "બધા લોકો", farmers: "ખેડૂતો", customers: "ગ્રાહકો", products: "પાકની યાદી", orders: "ઓર્ડર", payments: "ચુકવણી", verify: "ખેડૂતની ચકાસણી", complaints: "ફરિયાદો", reports: "અહેવાલો", lots: "પાકની યાદી", gmv: "કુલ વેચાણ", buyers: "ગ્રાહકો", disputes: "બાકી ફરિયાદો", openTickets: "બાકી ફરિયાદો", compLede: "ઓર્ડર, પાક અથવા ચુકવણીની ફરિયાદો તપાસો.", settled: "ચૂકવણી પૂર્ણ", escrow: "ચકાસણી બાકી", openFarm: "ખાતું જુઓ", approve: "મંજૂર કરો", hold: "થોભાવો", all: "બધું", allRoles: "બધી ભૂમિકા", allCats: "બધા પાક", ready: "તૈયાર", draft: "મસદ્દો", queue: "અહેવાલ તૈયાર કરો", queued: "તૈયારીમાં", low: "ઓછો જથ્થો", searchPeople: "નામ અથવા ઈમેલ શોધો", searchLots: "પાક શોધો", peopleLede: "DIRECT FARM સાથે જોડાયેલા લોકોની માહિતી.", productsLede: "બધા પાક અને તેમની ઉપલબ્ધતા જુઓ.", ordersLede: "ગ્રાહકોના ઓર્ડર અને તેમની સ્થિતિ.", payLede: "ચુકવણીની સરળ અને સ્પષ્ટ માહિતી.", reportsLede: "પ્લેટફોર્મની કામગીરીના અહેવાલો.", verifyLede: "ખેડૂતની ઓળખ અને ખેતરની માહિતી ચકાસો.", loadingFarmers: "ચકાસણી માટેના ખેડૂતો લાવી રહ્યા છીએ...", noPendingFarmers: "હાલ કોઈ ખેડૂત ચકાસણી માટે બાકી નથી.", ordersLedeShort: "ઓર્ડરની હાલની સ્થિતિ જુઓ.", col: { order: "ઓર્ડર", farm: "ખેતર", buyer: "ગ્રાહક", amount: "રકમ", status: "સ્થિતિ", lot: "પાક", price: "ભાવ", stock: "જથ્થો", flags: "નોંધ", name: "નામ", role: "ભૂમિકા", place: "સ્થળ", joined: "જોડાયા", tx: "ચુકવણી", method: "રીત" }, vstatus: { pending: "બાકી", approved: "મંજૂર", held: "થોભાવેલું" }, tstatus: { open: "ખુલ્લી", looking: "તપાસમાં", closed: "બંધ" }, ustatus: { active: "ચાલુ", pending: "બાકી", suspended: "બંધ" }, ckind: { order: "ઓર્ડર", payment: "ચુકવણી", quality: "ગુણવત્તા", other: "અન્ય" }
  },
  admin: { title: "DIRECT FARM વહીવટ", subtitle: "ખેડૂત, ગ્રાહક, પાક અને ઓર્ડરની માહિતી સરળતાથી સંભાળો.", gmv: "કુલ વેચાણ", orders: "ઓર્ડર", farmers: "ચકાસાયેલા ખેડૂતો", buyers: "ગ્રાહકો", passports: "પાકની ઓળખ", disputes: "ફરિયાદો", review: "ચકાસણી માટેના ખેડૂત", approve: "મંજૂર કરો", hold: "થોભાવો" }
} as const;
